name: calculator
description: "A new Flutter calculator project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.1

dependencies:
  flutter:
    sdk: flutter

  math_expressions: ^2.4.0
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

  # Splash Screen
  flutter_native_splash: ^2.4.7

  # App Icon
  flutter_launcher_icons: ^0.14.4


flutter:
  uses-material-design: true

  assets:
    - assets/calculator.png


# ===============================
# SPLASH SCREEN CONFIG
# ===============================
flutter_native_splash:
  color: "#0F172A"
  image: assets/calculator.png

  android: true
  ios: true
  web: false

  android_12:
    color: "#0F172A"
    image: assets/calculator.png


# ===============================
# APP ICON CONFIG
# ===============================
flutter_icons:
  android: true
  ios: true
  image_path: assets/calculator.png
